# Generated by Django 5.1.5 on 2025-01-31 05:27

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default='https://foundr.com/wp-content/uploads/2021/09/Best-online-course-platforms.png', null=True, upload_to=students.models.student_name_dict),
        ),
    ]
