# Generated by Django 5.1.5 on 2025-02-01 04:55

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default='default/images_1.jpg', null=True, upload_to=students.models.student_name_dict),
        ),
    ]
